Consider the below code to answer further questions:
import numpy as np
list_ =  [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Ques1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans. Yes, there is a difference in the data type of variables list_ and array_list.
The variable list_ is a Python list, whereas the variable array_list is a NumPy array.


In [3]:
import numpy as np

list_ =  [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print('The data type of "list_" is :- ', type(list_))
print('The data type of "array_list" is :- ', type(array_list))

The data type of "list_" is :-  <class 'list'>
The data type of "array_list" is :-  <class 'numpy.ndarray'>


Ques2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [7]:
list_ = ['1' , '2' , '3' , '4' , '5' ]

for i in list_ :
    print('The data type of each and every element in "list_" ' , type(i))
    
array_list = np.array(object = list_)

for i in array_list :
    print('The data type of each and every element in "array_list" ' , type(i))

The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "array_list"  <class 'numpy.str_'>
The data type of each and every element in "array_list"  <class 'numpy.str_'>
The data type of each and every element in "array_list"  <class 'numpy.str_'>
The data type of each and every element in "array_list"  <class 'numpy.str_'>
The data type of each and every element in "array_list"  <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans.  Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list after making the following change:

In [13]:
list_ = ['1' , '2' , '3' , '4' , '5' ]

for i in list_ :
    print('The data type of each and every element in "list_" ' , type(i))
    
array_list = np.array(object = list_ , dtype = int)

for i in array_list :
    print('The data type of each and every element in "array_list" ' , type(i))

The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "list_"  <class 'str'>
The data type of each and every element in "array_list"  <class 'numpy.int64'>
The data type of each and every element in "array_list"  <class 'numpy.int64'>
The data type of each and every element in "array_list"  <class 'numpy.int64'>
The data type of each and every element in "array_list"  <class 'numpy.int64'>
The data type of each and every element in "array_list"  <class 'numpy.int64'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Ques4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [21]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array)

print('The shape of num_array : ' , np.shape(num_array))

print('The size of num_array : ' , np.size(num_array))

[[1 2 3]
 [4 5 6]]
The shape of num_array :  (2, 3)
The size of num_array :  6


Ques5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [25]:
import numpy as np

ar = np.zeros((3,3))

print(ar)

print('The size of matrix is : ' , ar.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The size of matrix is :  9


Ques6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [27]:
import numpy as np

ar1 = np.eye(5,5)

print(ar1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
